SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[usp_LoadMirror_Contact](@notificationId UNIQUEIDENTIFIER) AS 
MERGE SalesforceMirror.dbo.Contact as Destination USING ( SELECT jsonData.* FROM dbo.Notifications a CROSS APPLY OPENJSON(Payload) WITH (
Id nvarchar(100),
AccountId nvarchar(100),
Account_Source__c nvarchar(100),
Active__c double precision,
Admin__c bit,
Age__c double precision,
Alias__c nvarchar(100),
AssistantName nvarchar(100),
AssistantPhone nvarchar(100),
Birthdate datetime2,
CRM_Dynamics_Contact_Id__c nvarchar(100),
Club_Name__c nvarchar(100),
ContactIdentityStatus__c nvarchar(100),
CreatedById nvarchar(100),
CreatedDate datetime2,
Date_of_Death__c datetime2,
Department nvarchar(100),
Description nvarchar(100),
DoNotCall bit,
Email nvarchar(100),
EmailBouncedDate datetime2,
EmailBouncedReason nvarchar(100),
End_Date__c datetime2,
External_Id__c nvarchar(100),
Fax nvarchar(100),
FirstName nvarchar(100),
GHIN__c nvarchar(100),
GW_Volunteers__First_Volunteer_Date__c datetime2,
GW_Volunteers__Last_Volunteer_Date__c datetime2,
GW_Volunteers__Unique_Volunteer_Count__c double precision,
GW_Volunteers__Volunteer_Auto_Reminder_Email_Opt_Out__c bit,
GW_Volunteers__Volunteer_Availability__c nvarchar(100),
GW_Volunteers__Volunteer_Hours__c double precision,
GW_Volunteers__Volunteer_Last_Web_Signup_Date__c datetime2,
GW_Volunteers__Volunteer_Manager_Notes__c nvarchar(100),
GW_Volunteers__Volunteer_Notes__c nvarchar(100),
GW_Volunteers__Volunteer_Organization__c nvarchar(100),
GW_Volunteers__Volunteer_Skills__c nvarchar(100),
GW_Volunteers__Volunteer_Status__c nvarchar(100),
Gender__c nvarchar(100),
GigyaUid__c nvarchar(100),
Golfer_Id__c double precision,
Golfer__c bit,
GuardianContactSysID__c nvarchar(100),
Guardian__c nvarchar(100),
Handicap_Index_Type__c nvarchar(100),
HasOptedOutOfEmail bit,
HasOptedOutOfFax bit,
HomePhone nvarchar(100),
Inactive__c double precision,
IsDeleted bit,
IsEmailBounced bit,
Is_Guardian__c bit,
Jigsaw nvarchar(100),
JigsawContactId nvarchar(100),
LastActivityDate datetime2,
LastCURequestDate datetime2,
LastCUUpdateDate datetime2,
LastModifiedById nvarchar(100),
LastModifiedDate datetime2,
LastName nvarchar(100),
LastReferencedDate datetime2,
LastViewedDate datetime2,
LeadSource nvarchar(100),
Legacy_GHIN_ID__c nvarchar(100),
Lowest_18_HCP__c double precision,
Lowest_9_HCP__c double precision,
MailingCity nvarchar(100),
MailingCountry nvarchar(100),
MailingCountryCode nvarchar(100),
MailingGeocodeAccuracy nvarchar(100),
MailingLatitude double precision,
MailingLongitude double precision,
MailingPostalCode nvarchar(100),
MailingState nvarchar(100),
MailingStateCode nvarchar(100),
MailingStreet nvarchar(100),
MasterRecordId nvarchar(100),
Membership_Type__c nvarchar(100),
Merged_To__c nvarchar(100),
MiddleName nvarchar(100),
Minor_Contact_to_Gigya__c bit,
Minor_turned_18__c bit,
MobilePhone nvarchar(100),
OtherCity nvarchar(100),
OtherCountry nvarchar(100),
OtherCountryCode nvarchar(100),
OtherGeocodeAccuracy nvarchar(100),
OtherLatitude double precision,
OtherLongitude double precision,
OtherPhone nvarchar(100),
OtherPostalCode nvarchar(100),
OtherState nvarchar(100),
OtherStateCode nvarchar(100),
OtherStreet nvarchar(100),
OwnerId nvarchar(100),
Phone nvarchar(100),
PhotoUrl nvarchar(100),
Primary_Email__c nvarchar(100),
Profile_Name__c nvarchar(100),
RecordTypeId nvarchar(100),
ReportsToId nvarchar(100),
SRGA_Admin__c bit,
SRGA_dummy__c nvarchar(100),
Salutation nvarchar(100),
Secondary_Email__c nvarchar(100),
Send_Contact_to_Gigya__c bit,
Start_Date__c datetime2,
Status__c nvarchar(100),
Suffix__c nvarchar(100),
SystemModstamp datetime2,
Title nvarchar(100),
USGA_Id__c nvarchar(100),
Use_Secondary_Email__c bit,
npe01__AlternateEmail__c nvarchar(100),
npe01__HomeEmail__c nvarchar(100),
npe01__Home_Address__c nvarchar(100),
npe01__Last_Donation_Date__c datetime2,
npe01__Lifetime_Giving_History_Amount__c double precision,
npe01__Organization_Type__c nvarchar(100),
npe01__Other_Address__c nvarchar(100),
npe01__PreferredPhone__c nvarchar(100),
npe01__Preferred_Email__c nvarchar(100),
npe01__Primary_Address_Type__c nvarchar(100),
npe01__Private__c bit,
npe01__Secondary_Address_Type__c nvarchar(100),
npe01__SystemAccountProcessor__c nvarchar(100),
npe01__SystemIsIndividual__c bit,
npe01__Type_of_Account__c nvarchar(100),
npe01__WorkEmail__c nvarchar(100),
npe01__WorkPhone__c nvarchar(100),
npe01__Work_Address__c nvarchar(100),
npo02__AverageAmount__c double precision,
npo02__Best_Gift_Year_Total__c double precision,
npo02__Best_Gift_Year__c nvarchar(100),
npo02__FirstCloseDate__c datetime2,
npo02__Formula_HouseholdMailingAddress__c nvarchar(100),
npo02__Formula_HouseholdPhone__c nvarchar(100),
npo02__Household_Naming_Order__c double precision,
npo02__Household__c nvarchar(100),
npo02__LargestAmount__c double precision,
npo02__LastCloseDateHH__c datetime2,
npo02__LastCloseDate__c datetime2,
npo02__LastMembershipAmount__c double precision,
npo02__LastMembershipDate__c datetime2,
npo02__LastMembershipLevel__c nvarchar(100),
npo02__LastMembershipOrigin__c nvarchar(100),
npo02__LastOppAmount__c double precision,
npo02__MembershipEndDate__c datetime2,
npo02__MembershipJoinDate__c datetime2,
npo02__Naming_Exclusions__c nvarchar(100),
npo02__NumberOfClosedOpps__c double precision,
npo02__NumberOfMembershipOpps__c double precision,
npo02__OppAmount2YearsAgo__c double precision,
npo02__OppAmountLastNDays__c double precision,
npo02__OppAmountLastYearHH__c double precision,
npo02__OppAmountLastYear__c double precision,
npo02__OppAmountThisYearHH__c double precision,
npo02__OppAmountThisYear__c double precision,
npo02__OppsClosed2YearsAgo__c double precision,
npo02__OppsClosedLastNDays__c double precision,
npo02__OppsClosedLastYear__c double precision,
npo02__OppsClosedThisYear__c double precision,
npo02__SmallestAmount__c double precision,
npo02__Soft_Credit_Last_Year__c double precision,
npo02__Soft_Credit_This_Year__c double precision,
npo02__Soft_Credit_Total__c double precision,
npo02__Soft_Credit_Two_Years_Ago__c double precision,
npo02__SystemHouseholdProcessor__c nvarchar(100),
npo02__TotalMembershipOppAmount__c double precision,
npo02__TotalOppAmount__c double precision,
npo02__Total_Household_Gifts__c double precision,
npsp__Address_Verification_Status__c nvarchar(100),
npsp__Batch__c nvarchar(100),
npsp__Current_Address__c nvarchar(100),
npsp__Deceased__c bit,
npsp__Do_Not_Contact__c bit,
npsp__Exclude_from_Household_Formal_Greeting__c bit,
npsp__Exclude_from_Household_Informal_Greeting__c bit,
npsp__Exclude_from_Household_Name__c bit,
npsp__First_Soft_Credit_Amount__c double precision,
npsp__First_Soft_Credit_Date__c datetime2,
npsp__HHId__c nvarchar(100),
npsp__Largest_Soft_Credit_Amount__c double precision,
npsp__Largest_Soft_Credit_Date__c datetime2,
npsp__Last_Soft_Credit_Amount__c double precision,
npsp__Last_Soft_Credit_Date__c datetime2,
npsp__Number_of_Soft_Credits_Last_N_Days__c double precision,
npsp__Number_of_Soft_Credits_Last_Year__c double precision,
npsp__Number_of_Soft_Credits_This_Year__c double precision,
npsp__Number_of_Soft_Credits_Two_Years_Ago__c double precision,
npsp__Number_of_Soft_Credits__c double precision,
npsp__Primary_Affiliation__c nvarchar(100),
npsp__Primary_Contact__c bit,
npsp__Soft_Credit_Last_N_Days__c double precision,
npsp__is_Address_Override__c bit ) AS jsonData		
							WHERE NotificationType = 'Contact'
							AND ProcessedDate IS NULL
							AND a.NotificationId = @notificationId ) AS Source
							ON Destination.Id = Source.Id 
 WHEN MATCHED AND Destination.LastModifiedDate < Source.LastModifiedDate THEN UPDATE SET 
Destination.AccountId = Source.AccountId,
Destination.Account_Source__c = Source.Account_Source__c,
Destination.Active__c = Source.Active__c,
Destination.Admin__c = Source.Admin__c,
Destination.Age__c = Source.Age__c,
Destination.Alias__c = Source.Alias__c,
Destination.AssistantName = Source.AssistantName,
Destination.AssistantPhone = Source.AssistantPhone,
Destination.Birthdate = Source.Birthdate,
Destination.CRM_Dynamics_Contact_Id__c = Source.CRM_Dynamics_Contact_Id__c,
Destination.Club_Name__c = Source.Club_Name__c,
Destination.ContactIdentityStatus__c = Source.ContactIdentityStatus__c,
Destination.CreatedById = Source.CreatedById,
Destination.CreatedDate = Source.CreatedDate,
Destination.Date_of_Death__c = Source.Date_of_Death__c,
Destination.Department = Source.Department,
Destination.Description = Source.Description,
Destination.DoNotCall = Source.DoNotCall,
Destination.Email = Source.Email,
Destination.EmailBouncedDate = Source.EmailBouncedDate,
Destination.EmailBouncedReason = Source.EmailBouncedReason,
Destination.End_Date__c = Source.End_Date__c,
Destination.External_Id__c = Source.External_Id__c,
Destination.Fax = Source.Fax,
Destination.FirstName = Source.FirstName,
Destination.GHIN__c = Source.GHIN__c,
Destination.GW_Volunteers__First_Volunteer_Date__c = Source.GW_Volunteers__First_Volunteer_Date__c,
Destination.GW_Volunteers__Last_Volunteer_Date__c = Source.GW_Volunteers__Last_Volunteer_Date__c,
Destination.GW_Volunteers__Unique_Volunteer_Count__c = Source.GW_Volunteers__Unique_Volunteer_Count__c,
Destination.GW_Volunteers__Volunteer_Auto_Reminder_Email_Opt_Out__c = Source.GW_Volunteers__Volunteer_Auto_Reminder_Email_Opt_Out__c,
Destination.GW_Volunteers__Volunteer_Availability__c = Source.GW_Volunteers__Volunteer_Availability__c,
Destination.GW_Volunteers__Volunteer_Hours__c = Source.GW_Volunteers__Volunteer_Hours__c,
Destination.GW_Volunteers__Volunteer_Last_Web_Signup_Date__c = Source.GW_Volunteers__Volunteer_Last_Web_Signup_Date__c,
Destination.GW_Volunteers__Volunteer_Manager_Notes__c = Source.GW_Volunteers__Volunteer_Manager_Notes__c,
Destination.GW_Volunteers__Volunteer_Notes__c = Source.GW_Volunteers__Volunteer_Notes__c,
Destination.GW_Volunteers__Volunteer_Organization__c = Source.GW_Volunteers__Volunteer_Organization__c,
Destination.GW_Volunteers__Volunteer_Skills__c = Source.GW_Volunteers__Volunteer_Skills__c,
Destination.GW_Volunteers__Volunteer_Status__c = Source.GW_Volunteers__Volunteer_Status__c,
Destination.Gender__c = Source.Gender__c,
Destination.GigyaUid__c = Source.GigyaUid__c,
Destination.Golfer_Id__c = Source.Golfer_Id__c,
Destination.Golfer__c = Source.Golfer__c,
Destination.GuardianContactSysID__c = Source.GuardianContactSysID__c,
Destination.Guardian__c = Source.Guardian__c,
Destination.Handicap_Index_Type__c = Source.Handicap_Index_Type__c,
Destination.HasOptedOutOfEmail = Source.HasOptedOutOfEmail,
Destination.HasOptedOutOfFax = Source.HasOptedOutOfFax,
Destination.HomePhone = Source.HomePhone,
Destination.Inactive__c = Source.Inactive__c,
Destination.IsDeleted = Source.IsDeleted,
Destination.IsEmailBounced = Source.IsEmailBounced,
Destination.Is_Guardian__c = Source.Is_Guardian__c,
Destination.Jigsaw = Source.Jigsaw,
Destination.JigsawContactId = Source.JigsawContactId,
Destination.LastActivityDate = Source.LastActivityDate,
Destination.LastCURequestDate = Source.LastCURequestDate,
Destination.LastCUUpdateDate = Source.LastCUUpdateDate,
Destination.LastModifiedById = Source.LastModifiedById,
Destination.LastModifiedDate = Source.LastModifiedDate,
Destination.LastName = Source.LastName,
Destination.LastReferencedDate = Source.LastReferencedDate,
Destination.LastViewedDate = Source.LastViewedDate,
Destination.LeadSource = Source.LeadSource,
Destination.Legacy_GHIN_ID__c = Source.Legacy_GHIN_ID__c,
Destination.Lowest_18_HCP__c = Source.Lowest_18_HCP__c,
Destination.Lowest_9_HCP__c = Source.Lowest_9_HCP__c,
Destination.MailingCity = Source.MailingCity,
Destination.MailingCountry = Source.MailingCountry,
Destination.MailingCountryCode = Source.MailingCountryCode,
Destination.MailingGeocodeAccuracy = Source.MailingGeocodeAccuracy,
Destination.MailingLatitude = Source.MailingLatitude,
Destination.MailingLongitude = Source.MailingLongitude,
Destination.MailingPostalCode = Source.MailingPostalCode,
Destination.MailingState = Source.MailingState,
Destination.MailingStateCode = Source.MailingStateCode,
Destination.MailingStreet = Source.MailingStreet,
Destination.MasterRecordId = Source.MasterRecordId,
Destination.Membership_Type__c = Source.Membership_Type__c,
Destination.Merged_To__c = Source.Merged_To__c,
Destination.MiddleName = Source.MiddleName,
Destination.Minor_Contact_to_Gigya__c = Source.Minor_Contact_to_Gigya__c,
Destination.Minor_turned_18__c = Source.Minor_turned_18__c,
Destination.MobilePhone = Source.MobilePhone,
Destination.OtherCity = Source.OtherCity,
Destination.OtherCountry = Source.OtherCountry,
Destination.OtherCountryCode = Source.OtherCountryCode,
Destination.OtherGeocodeAccuracy = Source.OtherGeocodeAccuracy,
Destination.OtherLatitude = Source.OtherLatitude,
Destination.OtherLongitude = Source.OtherLongitude,
Destination.OtherPhone = Source.OtherPhone,
Destination.OtherPostalCode = Source.OtherPostalCode,
Destination.OtherState = Source.OtherState,
Destination.OtherStateCode = Source.OtherStateCode,
Destination.OtherStreet = Source.OtherStreet,
Destination.OwnerId = Source.OwnerId,
Destination.Phone = Source.Phone,
Destination.PhotoUrl = Source.PhotoUrl,
Destination.Primary_Email__c = Source.Primary_Email__c,
Destination.Profile_Name__c = Source.Profile_Name__c,
Destination.RecordTypeId = Source.RecordTypeId,
Destination.ReportsToId = Source.ReportsToId,
Destination.SRGA_Admin__c = Source.SRGA_Admin__c,
Destination.SRGA_dummy__c = Source.SRGA_dummy__c,
Destination.Salutation = Source.Salutation,
Destination.Secondary_Email__c = Source.Secondary_Email__c,
Destination.Send_Contact_to_Gigya__c = Source.Send_Contact_to_Gigya__c,
Destination.Start_Date__c = Source.Start_Date__c,
Destination.Status__c = Source.Status__c,
Destination.Suffix__c = Source.Suffix__c,
Destination.SystemModstamp = Source.SystemModstamp,
Destination.Title = Source.Title,
Destination.USGA_Id__c = Source.USGA_Id__c,
Destination.Use_Secondary_Email__c = Source.Use_Secondary_Email__c,
Destination.npe01__AlternateEmail__c = Source.npe01__AlternateEmail__c,
Destination.npe01__HomeEmail__c = Source.npe01__HomeEmail__c,
Destination.npe01__Home_Address__c = Source.npe01__Home_Address__c,
Destination.npe01__Last_Donation_Date__c = Source.npe01__Last_Donation_Date__c,
Destination.npe01__Lifetime_Giving_History_Amount__c = Source.npe01__Lifetime_Giving_History_Amount__c,
Destination.npe01__Organization_Type__c = Source.npe01__Organization_Type__c,
Destination.npe01__Other_Address__c = Source.npe01__Other_Address__c,
Destination.npe01__PreferredPhone__c = Source.npe01__PreferredPhone__c,
Destination.npe01__Preferred_Email__c = Source.npe01__Preferred_Email__c,
Destination.npe01__Primary_Address_Type__c = Source.npe01__Primary_Address_Type__c,
Destination.npe01__Private__c = Source.npe01__Private__c,
Destination.npe01__Secondary_Address_Type__c = Source.npe01__Secondary_Address_Type__c,
Destination.npe01__SystemAccountProcessor__c = Source.npe01__SystemAccountProcessor__c,
Destination.npe01__SystemIsIndividual__c = Source.npe01__SystemIsIndividual__c,
Destination.npe01__Type_of_Account__c = Source.npe01__Type_of_Account__c,
Destination.npe01__WorkEmail__c = Source.npe01__WorkEmail__c,
Destination.npe01__WorkPhone__c = Source.npe01__WorkPhone__c,
Destination.npe01__Work_Address__c = Source.npe01__Work_Address__c,
Destination.npo02__AverageAmount__c = Source.npo02__AverageAmount__c,
Destination.npo02__Best_Gift_Year_Total__c = Source.npo02__Best_Gift_Year_Total__c,
Destination.npo02__Best_Gift_Year__c = Source.npo02__Best_Gift_Year__c,
Destination.npo02__FirstCloseDate__c = Source.npo02__FirstCloseDate__c,
Destination.npo02__Formula_HouseholdMailingAddress__c = Source.npo02__Formula_HouseholdMailingAddress__c,
Destination.npo02__Formula_HouseholdPhone__c = Source.npo02__Formula_HouseholdPhone__c,
Destination.npo02__Household_Naming_Order__c = Source.npo02__Household_Naming_Order__c,
Destination.npo02__Household__c = Source.npo02__Household__c,
Destination.npo02__LargestAmount__c = Source.npo02__LargestAmount__c,
Destination.npo02__LastCloseDateHH__c = Source.npo02__LastCloseDateHH__c,
Destination.npo02__LastCloseDate__c = Source.npo02__LastCloseDate__c,
Destination.npo02__LastMembershipAmount__c = Source.npo02__LastMembershipAmount__c,
Destination.npo02__LastMembershipDate__c = Source.npo02__LastMembershipDate__c,
Destination.npo02__LastMembershipLevel__c = Source.npo02__LastMembershipLevel__c,
Destination.npo02__LastMembershipOrigin__c = Source.npo02__LastMembershipOrigin__c,
Destination.npo02__LastOppAmount__c = Source.npo02__LastOppAmount__c,
Destination.npo02__MembershipEndDate__c = Source.npo02__MembershipEndDate__c,
Destination.npo02__MembershipJoinDate__c = Source.npo02__MembershipJoinDate__c,
Destination.npo02__Naming_Exclusions__c = Source.npo02__Naming_Exclusions__c,
Destination.npo02__NumberOfClosedOpps__c = Source.npo02__NumberOfClosedOpps__c,
Destination.npo02__NumberOfMembershipOpps__c = Source.npo02__NumberOfMembershipOpps__c,
Destination.npo02__OppAmount2YearsAgo__c = Source.npo02__OppAmount2YearsAgo__c,
Destination.npo02__OppAmountLastNDays__c = Source.npo02__OppAmountLastNDays__c,
Destination.npo02__OppAmountLastYearHH__c = Source.npo02__OppAmountLastYearHH__c,
Destination.npo02__OppAmountLastYear__c = Source.npo02__OppAmountLastYear__c,
Destination.npo02__OppAmountThisYearHH__c = Source.npo02__OppAmountThisYearHH__c,
Destination.npo02__OppAmountThisYear__c = Source.npo02__OppAmountThisYear__c,
Destination.npo02__OppsClosed2YearsAgo__c = Source.npo02__OppsClosed2YearsAgo__c,
Destination.npo02__OppsClosedLastNDays__c = Source.npo02__OppsClosedLastNDays__c,
Destination.npo02__OppsClosedLastYear__c = Source.npo02__OppsClosedLastYear__c,
Destination.npo02__OppsClosedThisYear__c = Source.npo02__OppsClosedThisYear__c,
Destination.npo02__SmallestAmount__c = Source.npo02__SmallestAmount__c,
Destination.npo02__Soft_Credit_Last_Year__c = Source.npo02__Soft_Credit_Last_Year__c,
Destination.npo02__Soft_Credit_This_Year__c = Source.npo02__Soft_Credit_This_Year__c,
Destination.npo02__Soft_Credit_Total__c = Source.npo02__Soft_Credit_Total__c,
Destination.npo02__Soft_Credit_Two_Years_Ago__c = Source.npo02__Soft_Credit_Two_Years_Ago__c,
Destination.npo02__SystemHouseholdProcessor__c = Source.npo02__SystemHouseholdProcessor__c,
Destination.npo02__TotalMembershipOppAmount__c = Source.npo02__TotalMembershipOppAmount__c,
Destination.npo02__TotalOppAmount__c = Source.npo02__TotalOppAmount__c,
Destination.npo02__Total_Household_Gifts__c = Source.npo02__Total_Household_Gifts__c,
Destination.npsp__Address_Verification_Status__c = Source.npsp__Address_Verification_Status__c,
Destination.npsp__Batch__c = Source.npsp__Batch__c,
Destination.npsp__Current_Address__c = Source.npsp__Current_Address__c,
Destination.npsp__Deceased__c = Source.npsp__Deceased__c,
Destination.npsp__Do_Not_Contact__c = Source.npsp__Do_Not_Contact__c,
Destination.npsp__Exclude_from_Household_Formal_Greeting__c = Source.npsp__Exclude_from_Household_Formal_Greeting__c,
Destination.npsp__Exclude_from_Household_Informal_Greeting__c = Source.npsp__Exclude_from_Household_Informal_Greeting__c,
Destination.npsp__Exclude_from_Household_Name__c = Source.npsp__Exclude_from_Household_Name__c,
Destination.npsp__First_Soft_Credit_Amount__c = Source.npsp__First_Soft_Credit_Amount__c,
Destination.npsp__First_Soft_Credit_Date__c = Source.npsp__First_Soft_Credit_Date__c,
Destination.npsp__HHId__c = Source.npsp__HHId__c,
Destination.npsp__Largest_Soft_Credit_Amount__c = Source.npsp__Largest_Soft_Credit_Amount__c,
Destination.npsp__Largest_Soft_Credit_Date__c = Source.npsp__Largest_Soft_Credit_Date__c,
Destination.npsp__Last_Soft_Credit_Amount__c = Source.npsp__Last_Soft_Credit_Amount__c,
Destination.npsp__Last_Soft_Credit_Date__c = Source.npsp__Last_Soft_Credit_Date__c,
Destination.npsp__Number_of_Soft_Credits_Last_N_Days__c = Source.npsp__Number_of_Soft_Credits_Last_N_Days__c,
Destination.npsp__Number_of_Soft_Credits_Last_Year__c = Source.npsp__Number_of_Soft_Credits_Last_Year__c,
Destination.npsp__Number_of_Soft_Credits_This_Year__c = Source.npsp__Number_of_Soft_Credits_This_Year__c,
Destination.npsp__Number_of_Soft_Credits_Two_Years_Ago__c = Source.npsp__Number_of_Soft_Credits_Two_Years_Ago__c,
Destination.npsp__Number_of_Soft_Credits__c = Source.npsp__Number_of_Soft_Credits__c,
Destination.npsp__Primary_Affiliation__c = Source.npsp__Primary_Affiliation__c,
Destination.npsp__Primary_Contact__c = Source.npsp__Primary_Contact__c,
Destination.npsp__Soft_Credit_Last_N_Days__c = Source.npsp__Soft_Credit_Last_N_Days__c,
Destination.npsp__is_Address_Override__c = Source.npsp__is_Address_Override__c
 WHEN NOT MATCHED THEN INSERT (Id, AccountId, Account_Source__c, Active__c, Admin__c, Age__c, Alias__c, AssistantName, AssistantPhone, Birthdate, CRM_Dynamics_Contact_Id__c, Club_Name__c, ContactIdentityStatus__c, CreatedById, CreatedDate, Date_of_Death__c, Department, Description, DoNotCall, Email, EmailBouncedDate, EmailBouncedReason, End_Date__c, External_Id__c, Fax, FirstName, GHIN__c, GW_Volunteers__First_Volunteer_Date__c, GW_Volunteers__Last_Volunteer_Date__c, GW_Volunteers__Unique_Volunteer_Count__c, GW_Volunteers__Volunteer_Auto_Reminder_Email_Opt_Out__c, GW_Volunteers__Volunteer_Availability__c, GW_Volunteers__Volunteer_Hours__c, GW_Volunteers__Volunteer_Last_Web_Signup_Date__c, GW_Volunteers__Volunteer_Manager_Notes__c, GW_Volunteers__Volunteer_Notes__c, GW_Volunteers__Volunteer_Organization__c, GW_Volunteers__Volunteer_Skills__c, GW_Volunteers__Volunteer_Status__c, Gender__c, GigyaUid__c, Golfer_Id__c, Golfer__c, GuardianContactSysID__c, Guardian__c, Handicap_Index_Type__c, HasOptedOutOfEmail, HasOptedOutOfFax, HomePhone, Inactive__c, IsDeleted, IsEmailBounced, Is_Guardian__c, Jigsaw, JigsawContactId, LastActivityDate, LastCURequestDate, LastCUUpdateDate, LastModifiedById, LastModifiedDate, LastName, LastReferencedDate, LastViewedDate, LeadSource, Legacy_GHIN_ID__c, Lowest_18_HCP__c, Lowest_9_HCP__c, MailingCity, MailingCountry, MailingCountryCode, MailingGeocodeAccuracy, MailingLatitude, MailingLongitude, MailingPostalCode, MailingState, MailingStateCode, MailingStreet, MasterRecordId, Membership_Type__c, Merged_To__c, MiddleName, Minor_Contact_to_Gigya__c, Minor_turned_18__c, MobilePhone, OtherCity, OtherCountry, OtherCountryCode, OtherGeocodeAccuracy, OtherLatitude, OtherLongitude, OtherPhone, OtherPostalCode, OtherState, OtherStateCode, OtherStreet, OwnerId, Phone, PhotoUrl, Primary_Email__c, Profile_Name__c, RecordTypeId, ReportsToId, SRGA_Admin__c, SRGA_dummy__c, Salutation, Secondary_Email__c, Send_Contact_to_Gigya__c, Start_Date__c, Status__c, Suffix__c, SystemModstamp, Title, USGA_Id__c, Use_Secondary_Email__c, npe01__AlternateEmail__c, npe01__HomeEmail__c, npe01__Home_Address__c, npe01__Last_Donation_Date__c, npe01__Lifetime_Giving_History_Amount__c, npe01__Organization_Type__c, npe01__Other_Address__c, npe01__PreferredPhone__c, npe01__Preferred_Email__c, npe01__Primary_Address_Type__c, npe01__Private__c, npe01__Secondary_Address_Type__c, npe01__SystemAccountProcessor__c, npe01__SystemIsIndividual__c, npe01__Type_of_Account__c, npe01__WorkEmail__c, npe01__WorkPhone__c, npe01__Work_Address__c, npo02__AverageAmount__c, npo02__Best_Gift_Year_Total__c, npo02__Best_Gift_Year__c, npo02__FirstCloseDate__c, npo02__Formula_HouseholdMailingAddress__c, npo02__Formula_HouseholdPhone__c, npo02__Household_Naming_Order__c, npo02__Household__c, npo02__LargestAmount__c, npo02__LastCloseDateHH__c, npo02__LastCloseDate__c, npo02__LastMembershipAmount__c, npo02__LastMembershipDate__c, npo02__LastMembershipLevel__c, npo02__LastMembershipOrigin__c, npo02__LastOppAmount__c, npo02__MembershipEndDate__c, npo02__MembershipJoinDate__c, npo02__Naming_Exclusions__c, npo02__NumberOfClosedOpps__c, npo02__NumberOfMembershipOpps__c, npo02__OppAmount2YearsAgo__c, npo02__OppAmountLastNDays__c, npo02__OppAmountLastYearHH__c, npo02__OppAmountLastYear__c, npo02__OppAmountThisYearHH__c, npo02__OppAmountThisYear__c, npo02__OppsClosed2YearsAgo__c, npo02__OppsClosedLastNDays__c, npo02__OppsClosedLastYear__c, npo02__OppsClosedThisYear__c, npo02__SmallestAmount__c, npo02__Soft_Credit_Last_Year__c, npo02__Soft_Credit_This_Year__c, npo02__Soft_Credit_Total__c, npo02__Soft_Credit_Two_Years_Ago__c, npo02__SystemHouseholdProcessor__c, npo02__TotalMembershipOppAmount__c, npo02__TotalOppAmount__c, npo02__Total_Household_Gifts__c, npsp__Address_Verification_Status__c, npsp__Batch__c, npsp__Current_Address__c, npsp__Deceased__c, npsp__Do_Not_Contact__c, npsp__Exclude_from_Household_Formal_Greeting__c, npsp__Exclude_from_Household_Informal_Greeting__c, npsp__Exclude_from_Household_Name__c, npsp__First_Soft_Credit_Amount__c, npsp__First_Soft_Credit_Date__c, npsp__HHId__c, npsp__Largest_Soft_Credit_Amount__c, npsp__Largest_Soft_Credit_Date__c, npsp__Last_Soft_Credit_Amount__c, npsp__Last_Soft_Credit_Date__c, npsp__Number_of_Soft_Credits_Last_N_Days__c, npsp__Number_of_Soft_Credits_Last_Year__c, npsp__Number_of_Soft_Credits_This_Year__c, npsp__Number_of_Soft_Credits_Two_Years_Ago__c, npsp__Number_of_Soft_Credits__c, npsp__Primary_Affiliation__c, npsp__Primary_Contact__c, npsp__Soft_Credit_Last_N_Days__c, npsp__is_Address_Override__c)
 VALUES (Source.Id, Source.AccountId, Source.Account_Source__c, Source.Active__c, Source.Admin__c, Source.Age__c, Source.Alias__c, Source.AssistantName, Source.AssistantPhone, Source.Birthdate, Source.CRM_Dynamics_Contact_Id__c, Source.Club_Name__c, Source.ContactIdentityStatus__c, Source.CreatedById, Source.CreatedDate, Source.Date_of_Death__c, Source.Department, Source.Description, Source.DoNotCall, Source.Email, Source.EmailBouncedDate, Source.EmailBouncedReason, Source.End_Date__c, Source.External_Id__c, Source.Fax, Source.FirstName, Source.GHIN__c, Source.GW_Volunteers__First_Volunteer_Date__c, Source.GW_Volunteers__Last_Volunteer_Date__c, Source.GW_Volunteers__Unique_Volunteer_Count__c, Source.GW_Volunteers__Volunteer_Auto_Reminder_Email_Opt_Out__c, Source.GW_Volunteers__Volunteer_Availability__c, Source.GW_Volunteers__Volunteer_Hours__c, Source.GW_Volunteers__Volunteer_Last_Web_Signup_Date__c, Source.GW_Volunteers__Volunteer_Manager_Notes__c, Source.GW_Volunteers__Volunteer_Notes__c, Source.GW_Volunteers__Volunteer_Organization__c, Source.GW_Volunteers__Volunteer_Skills__c, Source.GW_Volunteers__Volunteer_Status__c, Source.Gender__c, Source.GigyaUid__c, Source.Golfer_Id__c, Source.Golfer__c, Source.GuardianContactSysID__c, Source.Guardian__c, Source.Handicap_Index_Type__c, Source.HasOptedOutOfEmail, Source.HasOptedOutOfFax, Source.HomePhone, Source.Inactive__c, Source.IsDeleted, Source.IsEmailBounced, Source.Is_Guardian__c, Source.Jigsaw, Source.JigsawContactId, Source.LastActivityDate, Source.LastCURequestDate, Source.LastCUUpdateDate, Source.LastModifiedById, Source.LastModifiedDate, Source.LastName, Source.LastReferencedDate, Source.LastViewedDate, Source.LeadSource, Source.Legacy_GHIN_ID__c, Source.Lowest_18_HCP__c, Source.Lowest_9_HCP__c, Source.MailingCity, Source.MailingCountry, Source.MailingCountryCode, Source.MailingGeocodeAccuracy, Source.MailingLatitude, Source.MailingLongitude, Source.MailingPostalCode, Source.MailingState, Source.MailingStateCode, Source.MailingStreet, Source.MasterRecordId, Source.Membership_Type__c, Source.Merged_To__c, Source.MiddleName, Source.Minor_Contact_to_Gigya__c, Source.Minor_turned_18__c, Source.MobilePhone, Source.OtherCity, Source.OtherCountry, Source.OtherCountryCode, Source.OtherGeocodeAccuracy, Source.OtherLatitude, Source.OtherLongitude, Source.OtherPhone, Source.OtherPostalCode, Source.OtherState, Source.OtherStateCode, Source.OtherStreet, Source.OwnerId, Source.Phone, Source.PhotoUrl, Source.Primary_Email__c, Source.Profile_Name__c, Source.RecordTypeId, Source.ReportsToId, Source.SRGA_Admin__c, Source.SRGA_dummy__c, Source.Salutation, Source.Secondary_Email__c, Source.Send_Contact_to_Gigya__c, Source.Start_Date__c, Source.Status__c, Source.Suffix__c, Source.SystemModstamp, Source.Title, Source.USGA_Id__c, Source.Use_Secondary_Email__c, Source.npe01__AlternateEmail__c, Source.npe01__HomeEmail__c, Source.npe01__Home_Address__c, Source.npe01__Last_Donation_Date__c, Source.npe01__Lifetime_Giving_History_Amount__c, Source.npe01__Organization_Type__c, Source.npe01__Other_Address__c, Source.npe01__PreferredPhone__c, Source.npe01__Preferred_Email__c, Source.npe01__Primary_Address_Type__c, Source.npe01__Private__c, Source.npe01__Secondary_Address_Type__c, Source.npe01__SystemAccountProcessor__c, Source.npe01__SystemIsIndividual__c, Source.npe01__Type_of_Account__c, Source.npe01__WorkEmail__c, Source.npe01__WorkPhone__c, Source.npe01__Work_Address__c, Source.npo02__AverageAmount__c, Source.npo02__Best_Gift_Year_Total__c, Source.npo02__Best_Gift_Year__c, Source.npo02__FirstCloseDate__c, Source.npo02__Formula_HouseholdMailingAddress__c, Source.npo02__Formula_HouseholdPhone__c, Source.npo02__Household_Naming_Order__c, Source.npo02__Household__c, Source.npo02__LargestAmount__c, Source.npo02__LastCloseDateHH__c, Source.npo02__LastCloseDate__c, Source.npo02__LastMembershipAmount__c, Source.npo02__LastMembershipDate__c, Source.npo02__LastMembershipLevel__c, Source.npo02__LastMembershipOrigin__c, Source.npo02__LastOppAmount__c, Source.npo02__MembershipEndDate__c, Source.npo02__MembershipJoinDate__c, Source.npo02__Naming_Exclusions__c, Source.npo02__NumberOfClosedOpps__c, Source.npo02__NumberOfMembershipOpps__c, Source.npo02__OppAmount2YearsAgo__c, Source.npo02__OppAmountLastNDays__c, Source.npo02__OppAmountLastYearHH__c, Source.npo02__OppAmountLastYear__c, Source.npo02__OppAmountThisYearHH__c, Source.npo02__OppAmountThisYear__c, Source.npo02__OppsClosed2YearsAgo__c, Source.npo02__OppsClosedLastNDays__c, Source.npo02__OppsClosedLastYear__c, Source.npo02__OppsClosedThisYear__c, Source.npo02__SmallestAmount__c, Source.npo02__Soft_Credit_Last_Year__c, Source.npo02__Soft_Credit_This_Year__c, Source.npo02__Soft_Credit_Total__c, Source.npo02__Soft_Credit_Two_Years_Ago__c, Source.npo02__SystemHouseholdProcessor__c, Source.npo02__TotalMembershipOppAmount__c, Source.npo02__TotalOppAmount__c, Source.npo02__Total_Household_Gifts__c, Source.npsp__Address_Verification_Status__c, Source.npsp__Batch__c, Source.npsp__Current_Address__c, Source.npsp__Deceased__c, Source.npsp__Do_Not_Contact__c, Source.npsp__Exclude_from_Household_Formal_Greeting__c, Source.npsp__Exclude_from_Household_Informal_Greeting__c, Source.npsp__Exclude_from_Household_Name__c, Source.npsp__First_Soft_Credit_Amount__c, Source.npsp__First_Soft_Credit_Date__c, Source.npsp__HHId__c, Source.npsp__Largest_Soft_Credit_Amount__c, Source.npsp__Largest_Soft_Credit_Date__c, Source.npsp__Last_Soft_Credit_Amount__c, Source.npsp__Last_Soft_Credit_Date__c, Source.npsp__Number_of_Soft_Credits_Last_N_Days__c, Source.npsp__Number_of_Soft_Credits_Last_Year__c, Source.npsp__Number_of_Soft_Credits_This_Year__c, Source.npsp__Number_of_Soft_Credits_Two_Years_Ago__c, Source.npsp__Number_of_Soft_Credits__c, Source.npsp__Primary_Affiliation__c, Source.npsp__Primary_Contact__c, Source.npsp__Soft_Credit_Last_N_Days__c, Source.npsp__is_Address_Override__c)
;

 UPDATE Notifications SET ProcessedDate = SYSUTCDATETIME() WHERE NotificationId = @notificationId 
GO
GRANT EXECUTE ON  [dbo].[usp_LoadMirror_Contact] TO [CRMListenerWrite]
GO
